global:
  scrape_interval: 1m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:5000"]
  - job_name: node-exporter
  
    static_configs:
      - targets: ["node-exporter:9100"]

